version: "3.8"

services:
  nginx:
    image: openresty/openresty:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./scripts/purge.lua:/etc/lua/purge.lua
      - ./cache:/var/cache/nginx
    ports:
      - "80:80"
    networks:
      - app-network
    command: sh -c "nginx -g 'daemon off;'"

  backend:
    image: httpd:latest
    container_name: backend
    volumes:
      - ./images:/usr/local/apache2/htdocs:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
