version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_cache
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cache:/var/cache/nginx
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    image: httpd:latest
    container_name: backend
    volumes:
      - ./backend/images:/usr/local/apache2/htdocs:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
